---
title: "Lab 1 - Data visualization"
author: "Deandra Rasheesa Maheswari"
format: pdf
editor: visual
---

# Questions

## Part 1

```{r}
library(tidyverse)
```

### Question 1

Binwidth = 100

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 100) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 100"
  )
```

Binwidth = 1000

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 1000) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 1000"
  )
```

Binwidth = 10,000

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 10000) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 10,000"
  )
```

Binwdith = 100,000

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 100000) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 100,000"
  )
```

Comment: A graph with banwidth 1,000 is the most appropriate because it shows the overall distribution clearly without losing important detail, not too noisy nor oversmooth.

### Question 2

### Question 3

### Question 4

### Question 5

### Question 6

### Question 7

## Part 2

**Enough about the Midwest!**

### Question 8

### Question 9
